name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install linting tools
      run: |
        python -m pip install --no-cache-dir --force-reinstall flake8==5.0.4 pycodestyle==2.9.1 pyflakes==2.5.0 mccabe==0.7.0

    - name: Install testing tools
      run: |
        python -m pip install --no-cache-dir pytest==7.1.3 pytest-cov==3.0.0 coverage==6.5.0

    - name: Verify installations
      run: |
        python --version
        pip list
        which python
        python -c "import sys; print('Python executable:', sys.executable)"
        python -c "import flake8; print('flake8 version:', flake8.__version__)"
        python -c "import pytest; print('pytest version:', pytest.__version__)"
        python -m flake8 --version
        python -m pytest --version

    - name: Run linting
      run: |
        python -m flake8 consolidated_event_scraper.py --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 consolidated_event_scraper.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        python -m pytest --cov=consolidated_event_scraper --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
